image: ubuntu:bionic

pipelines:
  default:
    - step:
        script:
          - apt-get update -q -y
          - apt-get install -y libc++-dev libc++abi-dev libstdc++ g++
          - apt-get install git python3-setuptools python3-pip python3-dev -q -y
          - apt-get install libhdf5-serial-dev libnetcdf-dev python3-numpy libudunits2-dev -q -y
          - apt-get install libboost-date-time-dev -q -y
          - python setup.py build
          - python setup.py test
