image: ubuntu:eoan

pipelines:
  default:
    - step:
        script:
          - apt-get update -q -y
          - apt-get install -y libc++-dev g++ cmake
          - apt-get install git python3-pytest python3-setuptools python3-pip python3-dev -q -y
          - apt-get install libhdf5-serial-dev libnetcdf-dev python3-numpy libudunits2-dev -q -y
          - apt-get install python3-netcdf4 libboost-date-time-dev -q -y
          - git submodule init
          - git submodule update
          - python3 setup.py build
          - python3 setup.py test
