package:
  name: lagrangian
  version: 2.3.0

source:
  url: https://bitbucket.org/cnes_aviso/lagrangian/downloads/lagrangian-2.3.0.tar.gz

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cython
    - libnetcdf
    - libboost
    - netcdf4
    - netcdf-cxx4
    - numpy
    - python {{ python }}
    - setuptools
    - python-dateutil
    - udunits2
  run:
    - python {{ python }}
    - libnetcdf
    - libboost
    - netcdf-cxx4
    - netcdf4
    - numpy
    - python-dateutil
    - udunits2

test:
  imports:
    - lagrangian
