package:
  name: lagrangian
  version: 2.3.1

source:
        url: https://bitbucket.org/cnes_aviso/lagrangian/downloads/lagrangian-2.3.1.tar.gz
        sha256: c6541e36dc644a3f70d6a2e4dfed1db689c62d635668d2f0ce943420e4f585a4

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - cython
    - libboost
    - libnetcdf
    - netcdf4
    - numpy
    - python {{ python }}
    - python-dateutil
    - setuptools
    - udunits2
  run:
    - libboost
    - libnetcdf
    - netcdf4
    - numpy
    - python {{ python }}
    - python-dateutil
    - udunits2

test:
  imports:
    - lagrangian
