{% set data = load_setup_py_data() %}

package:
  name: lagrangian
  version: {{ data.get('version') }}

source:
  url: https://bitbucket.org/cnes_aviso/lagrangian/downloads/lagrangian-2.2.0.tar.gz

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cython
    - libnetcdf
    - libboost
    - netcdf4
    - netcdf-cxx4
    - numpy
    - python
    - setuptools
    - python-dateutil
    - udunits2
  run:
    - libnetcdf
    - libboost
    - netcdf-cxx4
    - netcdf4
    - numpy
    - python-dateutil
    - udunits2

test:
  imports:
    - lagrangian
