package:
  name: lagrangian
  version: "2.1.1"

source:
  hg_url: https://bitbucket.org/cnes_aviso/lagrangian
  hg_tag: "2.1.1"

requirements:
  build:
    - python
    - cython
    - numpy
    - setuptools
    - udunits2
    - libnetcdf
    - netcdf-cxx4
    - libboost
  run:
    - numpy
    - udunits2
    - libnetcdf
    - libboost
    - netcdf-cxx4

test:
  imports:
    - lagrangian
  