from . import CoordinatesType, Field, UnitType, reader

class Python(Field):
    def __init__(self, *args, **kwargs) -> None: ...

class TimeSerie(Field):
    def __init__(self, configuration_file: str, unit_type: UnitType = ..., coordinates_type: CoordinatesType = ..., reader_type: reader.Type = ...) -> None: ...
    def end_time(self, *args, **kwargs): ...
    def start_time(self, *args, **kwargs): ...

class Vonkarman(Field):
    def __init__(self) -> None: ...
