name: Lagrangian
channels:
  - conda-forge
dependencies:
  - cmake
  - eigen
  - setuptools_scm
  - netcdf4
  - pytest
  - boost-cpp
  - cxx-compiler
  - make # [not win]
  - binutils # [not win]
  - sphinx
  - sphinx-book-theme
  - udunits2
  - dateutils
